DigiVal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('recognition.urls')),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/icon.png')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

recognition/urls.py
from django.conf.urls import url
from . import views

app_name='recognition';

urlpatterns = [
    url(r'^reset-password/$', views.ResetPasswordRequestView, name='reset_password'),
    url(r'^reset_password_confirm/(?P<uid>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView,name='reset_password_confirm'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^evaluate/$', views.evaluate, name='evaluate'),
    url(r'^questionbank/$', views.question, name='question'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^questionseries/$', views.questionseries, name='qs'),
    url(r'^student/$', views.view_student, name='view_student'),
    url(r'^userprofile/$', views.userprofile, name='userprofile'),
    url(r'^results/$', views.results, name='results'),
    url(r'^answerkeys/$',views.answerkeys, name='answerkeys'),
    url(r'^logout/$', views.logout, name="logout"),
    url('^$', views.login, name='login'),
]

recognition/models.py
from django.db import models

# Create your models here.


def upload_location(instance,filename):
    return "%s/%s/%s/%s" %(instance.qp_class ,instance.qp_subject, instance.qp_test_series,filename)


def upload_location2(instance,filename):
    return "%s/%s/%s" %(instance.student.s_class,instance.student.s_rollno,filename)


class Teacher(models.Model):
    t_id = models.AutoField(primary_key=True)
    t_name = models.CharField(max_length=128, null=True)
    t_email = models.EmailField(null=True)
    t_school_name = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.t_name


class Student(models.Model):
    s_id = models.AutoField(primary_key=True)
    s_rollno = models.IntegerField(null=True)
    s_name = models.CharField(max_length=128, null=True)
    s_class = models.IntegerField(null=True)
    s_school_name = models.CharField(max_length=128, null=True)

    def __str__(self):
        return self.s_name


class QuestionPaper(models.Model):
    qp_id=models.AutoField(primary_key=True)
    qp_subject = models.CharField(max_length=15, null=False, default='English')
    qp_test_series = models.CharField(max_length=15, null=False, default=1)
    question_paper = models.ImageField(upload_to=upload_location,
                                       null=True,
                                       blank=False,
                                       width_field="width_field",
                                       height_field="height_field")
    qp_class = models.IntegerField(null=False, default=1)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

    class Meta:
        unique_together = (('qp_subject', 'qp_test_series', 'qp_class'),)

    def __str__(self):
        return self.qp_subject +" "+self.qp_test_series


class QuestionBank(models.Model):
    q_id = models.AutoField(primary_key=True)
    qb_qno = models.CharField(max_length=5, null=False)
    qb = models.ForeignKey(QuestionPaper, on_delete=models.CASCADE)
    qb_answers = models.CharField(max_length=30, null=False)

    class Meta:
        unique_together = (('qb_qno', 'qb'),)

    def __str__(self):
        return self.qb.qp_subject +" "+self.qb.qp_test_series+' '+self.qb_qno+" "+ self.qb_answers


class AddQuestionBank(models.Model):

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    qp = models.ForeignKey(QuestionPaper,on_delete=models.CASCADE)

    def __str__(self):
        return  self.teacher.t_name


class StudentMarks(models.Model):
    question_paper = models.ForeignKey(QuestionPaper, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    marks = models.IntegerField(default=0, null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    answer_paper = models.ImageField(upload_to=upload_location2,
                                     null=True,
                                     blank=True,
                                     width_field="width_field",
                                     height_field="height_field")
    height_field = models.IntegerField(default=0, null=True)
    width_field = models.IntegerField(default=0, null=True)

    class Meta:
        unique_together = (('question_paper','student'),)


    def __str__(self):
        return self.student.s_name +" "+ self.question_paper.qp_subject

recognition/forms.py
from django import forms
from . import models
from .models import QuestionBank

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False, min_length=10, max_length=10)


class UploadQuestionBank(forms.Form):
    qp_subject=forms.CharField()
    qp_test_series=forms.IntegerField()
    qp_class=forms.IntegerField()
    question_paper=forms.ImageField()

class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)

class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
        }
    new_password1 = forms.CharField(label=("New password"),
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=("New password confirmation"),
                                    widget=forms.PasswordInput)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                    )
        return password2

recognition/views.py
import csv
import pandas
import re
import time

#gmail
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template import loader
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models.query_utils import Q
from django.views.generic import *
from django.contrib.auth.models import User

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from .forms import UploadQuestionBank, RegisterForm , SetPasswordForm, PasswordResetRequestForm
from .models import AddQuestionBank
from .models import QuestionBank, StudentMarks, Student, Teacher, QuestionPaper
from .recognize import recognize, evaluate_paper


# Create your views here.
def validate_email_address(email):
    #This method here validates the if the input is an email address or not. Its return type is boolean, True if the input is a email address or False if its not.

        try:
            validate_email(email)
            return True
        except ValidationError:
            return False


def ResetPasswordRequestView(request, *args, **kwargs):
    template = 'recognition/forgot_password.html'
    success_url = 'recognition/Sign_in.html'

    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data["email_or_username"]
        if validate_email_address(data) is True:
            associated_users = User.objects.filter(Q(email=data) | Q(username=data))
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': request.META['HTTP_HOST'],
                        'site_name': 'Digival',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email_template_name = 'recognition/password_reset_email.html'
                    email = loader.render_to_string(email_template_name, c)
                    send_mail('Reset Password', email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                messages.success(request,'An email has been sent to ' + data + ". Please check its inbox to continue reseting password.")
                return render(request, 'recognition/forgot_password.html', {'form': form})
            messages.error(request, 'No user is associated with this email address')
            return render(request, 'recognition/forgot_password.html', {'form': form})
        else:
            associated_users = User.objects.filter(username=data)
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': request.META['HTTP_HOST'],
                        'site_name': 'Digival',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email_template_name = 'recognition/password_reset_email.html'
                    email = loader.render_to_string(email_template_name, c)
                    send_mail('Reset Password', email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                messages.success(request,'Email has been sent to ' + data + "'s email address. Please check its inbox to continue reseting password.")
                return render(request, 'recognition/forgot_password.html', {'form': form})
            else:
                messages.error(request, 'This username does not exist in the system.')
                return render(request, 'recognition/forgot_password.html', {'form': form})
        messages.error(request, 'Invalid Input')
        return render(request, 'recognition/forgot_password.html', {'form': form})
    else:
        form = PasswordResetRequestForm()
    return render(request, template, {'form': form})


def PasswordResetConfirmView(request, uid = None, token = None, *args, **kwargs):
    if request.method == 'POST':
        UserModel = get_user_model()
        form = SetPasswordForm(request.POST)
        assert uid is not None and token is not None  # checked by URLconf
        try:
            uid = urlsafe_base64_decode(uid)
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            if form.is_valid():
                new_password = form.cleaned_data['new_password2']
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password has been reset.')
                return render(request, 'recognition/reset_password_confirm.html')
            else:
                messages.error(request, 'Password reset has not been successful.')
                return render(request, 'recognition/reset_password_confirm.html')
        else:
            messages.error(request, 'The reset password link is no longer valid.')
            return render(request, 'recognition/reset_password_confirm.html')
    else:
        form = SetPasswordForm()
    return render(request, 'recognition/reset_password_confirm.html', {'form': form})


def login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Save session as cookie to login the user
            auth_login(request, user)
            user_email = User.objects.get(username=username)
            teacher_id = Teacher.objects.get(t_email=user_email.email)
            request.session['t_id'] = teacher_id.t_id
            # Success, now let's login the user.
            return render(request, 'recognition/homepage.html')
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, 'recognition/Sign_in.html',
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'recognition/Sign_in.html')


def signup(request):
    template = 'recognition/signup.html'

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.phone_number = form.cleaned_data['phone_number']
                user.save()

                f_name = form.cleaned_data['first_name']
                l_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']

                #Login the user
                auth_login(request, user)
                teacher = Teacher.objects.create(t_name=f_name +" "+ l_name, t_email=email)
                # redirect to accounts page:
                return render(request, 'recognition/Sign_in.html')
            # return HttpResponseRedirect('recognition/Sign_in.html')

    # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

    # return render(request, 'recognition/signup.html')


def evaluate(request):
    show = 1
    messages = 0
    if not request.session.has_key('t_id'):
        return login(request)

    t_id = request.session['t_id']
    teacher = Teacher.objects.get(t_id=t_id)
    questionBank_subject = QuestionPaper.objects.values('qp_subject').distinct()
    questionBank_testseries = QuestionPaper.objects.values('qp_test_series').distinct()

    rollno = Student.objects.values('s_rollno').distinct()
    classes = QuestionPaper.objects.order_by('qp_class').values('qp_class').distinct()

recognition/templates/recognition/Sign_in.html
{% extends "recognition/base1.html" %}

{% block content %}

<div class="container" xmlns="http://www.w3.org/1999/html" >
        <form action="{% url 'recognition:login' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="font-size:25px;margin-left:-29px;font-weight:bold;">Login</div>

                    <hr style="margin-left:-60px; width:100%">
                    <div class="panel-body" style="width: 750px;margin-left: -65px;">
                    {% if error_message %}
                            <p class="text-danger p-d ml-b" style="width:400px;">{{ error_message }}</p>
                    {% endif %}

                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <div class="col-md-6">
                                <input name="password" type="password" class="form-control">
                            </div>
                        </div>

                        <div class="col-md-6 col-md-offset-4">
                            <center>
                            <input name="login" type="submit" value="Login" class="btn btn-success" style="background-color:#5680e9"> &nbsp;
                           <hr>
                            <p>Don't have an account? <a href="/signup/">Sign Up</a>.</p>
                            <a href="/reset-password/">Forgot your password?</a>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

recognition/templates/recognition/evaluate.html
{% load static %}

<html>
<head>
	<title>Digival</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/sign.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/loader.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
	<script type = "text/javascript">

        switch({{messages}})
        {
            case 1: alert('Unable to recognize any text in the image! Please try again!');
            break;
            case 2: alert('Please Upload an Image!');
            break;
			case 3: alert('Successfully Evaluated!');
			break;
			case 4: alert('Sorry! Test Series not available...Please Upload Question Bank!');
			break;
			case 5: alert('Sorry! Student not found.');
			break;
        	case 6: alert('Answer Sheet Already Uploaded');
			break;
        }


     function preventBack(){window.history.forward();}
    setTimeout("preventBack()", 0);
    window.onunload=function(){null};



</script>
	<script>

$('#loader').addClass("hide-loader");
$(".container").addClass("hide-container");
$(document).ready(function(){

$("#submitBtn").click(function(){
$("#loader").show();
$(".container").hide();
});
});

if ( {{show }} ){
$("#loader").hide();
$(".container").show();
}

	</script>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
</head>
<body  style="background-image:url(/static/images/blue5.jpg);" class="override">
<header>

		<table width='100%'>
			<tr>
				<td style="color: white;"><p><h1 class='h'>DIGIVAL</h1>
					<h3 class='h'>An Automated Evaluation System</h3></p></td>
					<td width="150px">
						<a href="{% url 'recognition:login' %}" id="logout">
						<table cellspacing="10pt">
						<tr>
							<td><img src="{% static 'images/user.png' %}" id='user'></td>
							<td><h2 style="color: white;" align="center">Logout</h2></td>
						</tr></table></a>
					</td>
			</tr>
		</table>
	</header>
<br><br>
	<div class="loader" id="loader" style="display:none"><img src="{% static 'images/loader.gif'%}"></div>
	<div class="container" style="width:40%;" >
		<h1 align="center">Evaluation</h1><hr>

		<form action='' method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<label><b>Choose Subject</b></label>
			<select name="subject">
				{% for entry in questionBank_subject %}
    				<option value="{{ entry.qp_subject }}">{{ entry.qp_subject }}</option>
				{% endfor %}
			</select>
			<label><b>Choose Test Series</b></label>
			<select name="testseries">
				{% for entry in questionBank_testseries %}
    				<option value="{{ entry.qp_test_series }}">{{ entry.qp_test_series }}</option>
				{% endfor %}
			</select>

			<label><b>Choose Class</b></label>
			<select name="class">
                {% for entry in class %}
    				<option value="{{ entry.qp_class }}">{{ entry.qp_class }}</option>
				{% endfor %}
			</select>

			<p><label><b>Upload Answer Sheet</b></label></p>
			<p><input id = "answer" type="file" name="answer" accept="image/*"></p>

			<label><b>Enter Roll Number</b></label>
			<select name="s_rollno">
                {% for rollno in r_no %}
    				<option value="{{ rollno.s_rollno }}">{{ rollno.s_rollno }}</option>

				{% endfor %}
			</select>
			<hr><center><input class="freeze" type="submit" value='Evaluate' id="submitBtn" ></center>



		</form>
		<center><a  href="{% url 'recognition:homepage' %}"><button id="backBtn">Back</button></a> </center>

	</div>
<br><br><br><br>
<footer>
		<hr>
		<p>
			<b>Contact Information</b>
			<table cellspacing="10px">
				<tr>
					<td><img src="{% static 'images/phone.png' %}" class='headfoot'></td>
					<td>+91 9876543210</td>
				</tr>
				<tr>
					<td><img src="{% static 'images/email.png' %}" class="headfoot"></td>
					<td>queries@digival.com</td>
				</tr>
			</table>

			<p style="background-color: black; color: white;" align="center">
				&copy Copyright All Rights Reserved | Designed By Digival
			</p>
		</p>
	</footer>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"></script>
</body>
</html>

recognition/templates/recognition/question.html
{% load static %}

<html>
<head>
	<title>Digival</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/sign.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
		<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
</head>
<body style="background-image:url(/static/images/blue3.jpg);">
<header>
		<table width='100%'>
			<tr>
				<td style="color: white;"><p><h1 class='h animated slideInLeft'>DIGIVAL</h1>
					<h3 class='h'>An Automated Evaluation System</h3></p></td>
			</tr>
		</table>
	</header><br><br><br>
<br><br>
	<div class="container" style="width:40%;">

		<h1 align="center">Upload Question Paper</h1><hr>
       <form action="{% url 'recognition:question' %}" enctype="multipart/form-data" method="post" >
		   {% csrf_token %}
		   {% if error_message %}
		   <p align="center" style="color:red;">{{ error_message }}</p>
		   {% endif %}
			<label><b>Enter Subject</b></label>
			<select name="qp_subject">
				<option value="English">English</option>
				<option value="GK">GK</option>
				<option value="EVS">EVS</option>
			</select>

			<label><b>Enter Test Series</b></label>
			<select name="qp_test_series">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
			</select>

			<label><b>Enter Class</b></label>
			<input type="text" name="qp_class" id="cls" value='' required="">


			<p><label><b>Upload Question Paper</b></label></p>
			<p><input id = "answer" type="file" name="question_paper" accept="image/*" required></p>
            <hr>

		    <input type="submit" value='Next' name = 'Next' id="submitBtn" style="background-color:#5680e9;color:white;"/>
        </form>
        <center><a  href="{% url 'recognition:homepage' %}"><button id="backBtn" style="background-color:#5680e9;color:white;padding:15px;">Back</button></a> </center>
    </div><br><br><br><br>
<footer>
		<hr>
		<p>
			<b>Contact Information</b>
			<table cellspacing="10px">
				<tr>
					<td><img src="{% static 'images/phone.png' %}" class='headfoot'></td>
					<td>+91 9876543210</td>
				</tr>
				<tr>
					<td><img src="{% static 'images/email.png' %}" class="headfoot"></td>
					<td>queries@digival.com</td>
				</tr>
			</table>

			<p style="background-color: black; color: white;" align="center">
				&copy Copyright All Rights Reserved | Designed By Digival
			</p>
		</p>
	</footer>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"></script>
</body>
</html>

recognition/templates/recognition/signup.html
{% extends "recognition/base.html" %}

{% block content %}
    <div class="container">
        <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>
        <form action="{% url 'recognition:signup' %}" method="post" >
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body" align="center" style="width: 150%">
                        {% if error_message %}
                            <p class="text-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}

                        <div class="form-group clearfix">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                            <div class="col-md-6">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                            <div class="col-md-6">
                                {{ form.password_repeat }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
                            <div class="col-md-6">
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
                            <div class="col-md-6">
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-right" >Phone Number:</label>
                            <div class="col-md-6">
                                {{ form.phone_number }}
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit"style="background-color:#5680e9;color:white;" value="Register" class="btn">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
<div class="container signin">
    <p>Already have an account? <a href="{% url 'recognition:login' %}">Sign in</a>.</p>
  </div>

{% endblock %}